const { nanoid } = require("nanoid")
const supertest = require("supertest")
const app = require("../app")
const testSetup = require("./test-setup")
const server = app.listen(3000)
const request = supertest(server)
testSetup(server)

describe("Go to main routes and have error? cause dont have error", () => {
    it("Token is required to protected routes", async () => {
        const response = await request.get("/").set("Accept", "application/json")
        expect(response.body.message && response.body.status).toBeTruthy()
        expect(response.body.status).toBe(403)
        expect(response.body.message).toMatch(/required/)
    })
    it("Token length will be more then 20", async () => {
        const response = await request.post("/")
            .set("Accept", "application/json")
            .send({ token: nanoid(17) })
        expect(response.body).toBeTruthy()
        expect(response.body.status).toBe(403)
        expect(response.body.message).toBeTruthy()
        expect(response.body.message).toMatch(/20/)
        expect(response.body.message.length).toBeGreaterThan(10)
        expect(response.body.message.length).toBeLessThan(80)
    })
})